apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: project-deployment 
spec: 
  selector: 
    matchLabels: 
      app: project 
  replicas: 3 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: project 
    spec: 
      containers: 
      - name: project 
        image: adiaby2609/project
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: project-service 
spec: 
  selector: 
    app: project 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 